@host=https://localhost:7133

POST {{host}}/api/inquiry/create
Content-Type: application/json

{
  "entityId": "12345678",
  "status": "New",
  "secondaryStatus": null,
  "contactName": "John Locke",
  "phoneNumber": "123455555"
}